### ISSUE TITLE
Is there any possibility of using this project on AMD GPU or iGPU?

### ISSUE THREAD

**Issue by ws2bhhh** [ourbunka/aidadiffusion#3]
I noticed that Direct-ML and onnx are used in the project, does this mean that it will be possible to run StableDiffusion with any AMD GPU or iGPU that supports Direct-ML in later versions?
If so, it would be quite exciting :D

**Comment by ourbunka** [comment]
yes, amd gpu is supported in V0.1.3-onnx branch [(This Branch)](https://github.com/ourbunka/aidadiffusion/tree/V0.1.3-ORT). So far, tested and run fine on AMD polaris, VEGA56/64 and RDNA1, but not RDNA2(seem to be driver issue?)

As for igpu, I'm not sure. Currently, I don't have cpu with igpu to test. haha

That said, for the past weeks, we tried to get stable diffusion v-1-5 to run through onnx, but failed... so we decide to split into 2 branch, cuda & onnx. 
For now, We will focus on cuda branch, onnx branch will stay at stablediffusion v-1-4.
